spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portfolio
    username: root
    password: master
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update